#!/bin/bash
# MIT License
# Copyright (c) 2022 Gauthier FRANCOIS

export RACK_ENV=production

# Mandatory for Ruby environment manager like RVM or RBENV
source ~/.bashrc

# Change home directory for Sinatra application
export HOME=/var/www/domogeek

if [ "$EUID" -eq 0 ]
  then echo "Please don't run as root"
  exit
fi

if [ -z $1 ]
then
  port=8082
else
  port=$1
fi

bundle exec rackup -p $port
